"""Abstract LLM client interface.

This module defines the :class:`LLMClient` abstract base class that decouples
tools (Creative_Generator, Localization_Tool, Compliance_Checker, etc.) from
the concrete LLM provider. Concrete implementations live alongside this file:

- :class:`creative_agent.llm.real_client.RealLLMClient` — production client
  that calls an OpenAI-compatible HTTP endpoint via ``httpx``.
- :class:`creative_agent.llm.mock_client.MockLLMClient` — deterministic mock
  used by unit / property tests.

The interface intentionally exposes only two coroutines — :meth:`complete`
returning free-form text and :meth:`complete_json` returning a parsed
``dict`` — which together cover every LLM-backed tool's needs without leaking
provider-specific concepts (function calling, streaming, etc.) into the rest
of the system.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional


class LLMClient(ABC):
    """Async LLM client abstraction shared by all tools.

    All implementations MUST be safe to call concurrently (the orchestrator
    fans out tool calls across candidates with :func:`asyncio.gather`).
    """

    @abstractmethod
    async def complete(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        max_tokens: int = 1024,
        temperature: float = 0.7,
        timeout_ms: Optional[int] = None,
    ) -> str:
        """Return the LLM's generated text for ``prompt``.

        Args:
            prompt: The user-role message content.
            system: Optional system-role message; omitted from the request
                when ``None``.
            max_tokens: Upper bound on tokens generated by the model.
            temperature: Sampling temperature in ``[0.0, 2.0]``.
            timeout_ms: Per-call timeout in milliseconds; implementations
                fall back to their own default when ``None``.

        Returns:
            The raw text content from the model's first choice.

        Raises:
            creative_agent.errors.codes.ToolFailureError: On any transport,
                timeout, or upstream error.
        """
        ...

    @abstractmethod
    async def complete_json(
        self,
        prompt: str,
        *,
        system: Optional[str] = None,
        max_tokens: int = 1024,
        temperature: float = 0.7,
        timeout_ms: Optional[int] = None,
    ) -> dict:
        """Return the LLM's response parsed as a JSON object.

        Implementations are expected to instruct the model to emit pure JSON
        and to tolerate common formatting noise (e.g. ``\u0060\u0060\u0060json`` fences).

        Args:
            prompt: The user-role message content.
            system: Optional system-role message; omitted when ``None``.
            max_tokens: Upper bound on tokens generated.
            temperature: Sampling temperature.
            timeout_ms: Per-call timeout in milliseconds.

        Returns:
            The parsed JSON dictionary.

        Raises:
            creative_agent.errors.codes.ToolFailureError: When the response
                cannot be parsed as JSON, or on any transport / upstream error.
        """
        ...
